vich_uploader:
    db_driver: orm

    metadata:
        type: annotation

    mappings:
        category_thumbnail:
            uri_prefix: '%category_images%'
            upload_destination: '%kernel.project_dir%/public%category_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

    