vich_uploader:
    db_driver: orm

    metadata:
        type: annotation

    mappings:
        categoryPictures:
            uri_prefix: /asset/images/category
            upload_destination: '%kernel.project_dir%/public/asset/images/category'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer